"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Customer = { id: string; name: string; phone: string | null; account_number: string | null; monthly_amount: number; start_date: string; active: boolean };
type Payment = { id: string; customer_id: string; amount: number; paid_on: string; month_for: string; notes: string | null };
const money = (n: number | string) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(n));
const month = () => new Date().toISOString().slice(0, 7) + "-01";

export default function Home() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [payments, setPayments] = useState<Payment[]>([]);
  const [email, setEmail] = useState(""); const [loading, setLoading] = useState(true); const [signedIn, setSignedIn] = useState(false); const [message, setMessage] = useState("");
  const [newCustomer, setNewCustomer] = useState({ name: "", phone: "", account_number: "", monthly_amount: "", start_date: new Date().toISOString().slice(0,10) });
  const [payment, setPayment] = useState({ customer_id: "", amount: "", paid_on: new Date().toISOString().slice(0,10), month_for: month(), notes: "" });
  const load = async () => { const [{ data: c }, { data: p }] = await Promise.all([supabase.from("rd_customers").select("*").order("name"), supabase.from("rd_payments").select("*").order("paid_on", { ascending: false })]); setCustomers(c ?? []); setPayments(p ?? []); setLoading(false); };
  useEffect(() => { supabase.auth.getUser().then(({data}) => { if (data.user) { setSignedIn(true); load(); } else setLoading(false); }); }, []);
  const paidThisMonth = useMemo(() => new Set(payments.filter(p => p.month_for === month()).map(p => p.customer_id)), [payments]);
  const signIn = async (e: FormEvent) => { e.preventDefault(); const { error } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: location.origin } }); setMessage(error?.message ?? "Check your email for the secure sign-in link."); };
  const addCustomer = async (e: FormEvent) => { e.preventDefault(); const { error } = await supabase.from("rd_customers").insert({ ...newCustomer, monthly_amount: Number(newCustomer.monthly_amount), phone: newCustomer.phone || null, account_number: newCustomer.account_number || null }); if (error) return setMessage(error.message); setNewCustomer({ name:"",phone:"",account_number:"",monthly_amount:"",start_date:new Date().toISOString().slice(0,10) }); await load(); };
  const recordPayment = async (e: FormEvent) => { e.preventDefault(); const { error } = await supabase.from("rd_payments").insert({ ...payment, amount: Number(payment.amount), notes: payment.notes || null }); if (error) return setMessage(error.message); setPayment({ customer_id:"", amount:"", paid_on:new Date().toISOString().slice(0,10), month_for:month(), notes:"" }); await load(); };
  if (loading) return <main className="center">Loading your ledger…</main>;
  if (!signedIn) return <main className="auth"><section><p className="eyebrow">RD LEDGER</p><h1>Every payment, clearly recorded.</h1><p>Private recurring-deposit customer register with permanent payment history.</p><form onSubmit={signIn}><label>Email address<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" /></label><button>Send secure sign-in link</button></form>{message && <p className="notice">{message}</p>}</section></main>;
  return <main><header><div><p className="eyebrow">RD LEDGER</p><h1>Monthly payments</h1><p>{customers.length} active customers · {paidThisMonth.size} paid for this month</p></div><button className="quiet" onClick={()=>supabase.auth.signOut().then(()=>location.reload())}>Sign out</button></header>
  <p className="notice">{message}</p><section className="grid"><form className="card" onSubmit={addCustomer}><h2>Add customer</h2><label>Full name<input required value={newCustomer.name} onChange={e=>setNewCustomer({...newCustomer,name:e.target.value})}/></label><label>Mobile number<input value={newCustomer.phone} onChange={e=>setNewCustomer({...newCustomer,phone:e.target.value})}/></label><label>RD / account number<input value={newCustomer.account_number} onChange={e=>setNewCustomer({...newCustomer,account_number:e.target.value})}/></label><label>Monthly RD amount (₹)<input type="number" min="1" required value={newCustomer.monthly_amount} onChange={e=>setNewCustomer({...newCustomer,monthly_amount:e.target.value})}/></label><label>Start date<input type="date" required value={newCustomer.start_date} onChange={e=>setNewCustomer({...newCustomer,start_date:e.target.value})}/></label><button>Add customer</button></form>
  <form className="card" onSubmit={recordPayment}><h2>Record payment</h2><label>Customer<select required value={payment.customer_id} onChange={e=>{const c=customers.find(x=>x.id===e.target.value); setPayment({...payment,customer_id:e.target.value,amount:c ? String(c.monthly_amount) : ""});}}><option value="">Choose customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} — {money(c.monthly_amount)}</option>)}</select></label><label>Amount received (₹)<input type="number" min="1" required value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label><label>Payment received on<input type="date" required value={payment.paid_on} onChange={e=>setPayment({...payment,paid_on:e.target.value})}/></label><label>Payment for month<input type="month" required value={payment.month_for.slice(0,7)} onChange={e=>setPayment({...payment,month_for:e.target.value+"-01"})}/></label><label>Notes (optional)<input value={payment.notes} onChange={e=>setPayment({...payment,notes:e.target.value})}/></label><button>Save payment</button></form></section>
  <section className="card"><h2>Customer status — {new Date().toLocaleString("en-IN", {month:"long",year:"numeric"})}</h2><div className="customers">{customers.map(c=><article key={c.id}><div><strong>{c.name}</strong><span>{c.account_number || c.phone || "No account/mobile recorded"}</span></div><b>{money(c.monthly_amount)}</b><em className={paidThisMonth.has(c.id)?"paid":"due"}>{paidThisMonth.has(c.id)?"Paid":"Due"}</em></article>)}</div></section>
  <section className="card"><h2>Payment history</h2><div className="history">{payments.map(p=>{const c=customers.find(x=>x.id===p.customer_id);return <article key={p.id}><strong>{c?.name ?? "Customer removed"}</strong><span>{new Date(p.month_for).toLocaleString("en-IN",{month:"short",year:"numeric"})} · received {new Date(p.paid_on).toLocaleDateString("en-IN")}{p.notes?` · ${p.notes}`:""}</span><b>{money(p.amount)}</b></article>})}{!payments.length&&<p>No payments recorded yet.</p>}</div></section></main>;
}
